### ISSUE TITLE
How to train the generative NeMF on dog mocap dataset?

### ISSUE THREAD

**Issue by jonggul2** [c-he/NeMF#21]
Hello, I would like to train a Generative NeMF model on dog mocap data, but only the code for training a Single-motion NeMF model is available. Could you provide the code for this, and also let me know if there is a pre-trained model available?

**Comment by c-he** [comment]
Hi, thanks for your interest in our project. Sorry that we don't have a pre-trained model on dog mocap data as we only use them for validation. You need to mofify our codebase to train this model, and the logic would be:
1. Modify `animal.py` to process all the dog mocap data and split them into the training/validation/testing sets (currently we process each sequence one by one and store them separately).
2. Modify `train.py` to load the processed `Animal` Dataset rather than `AMASS`, and write a corresponding config file to properly set the hyperparaemters.
3. Modify `train_gmp.py` to train it for the `Animal` Dataset rather than `AMASS`, a new config file would be required as well.
There might be other issues I overlooked, but the basic logic is here. If you run into any issues, welcome to point them out and I can help to resolve them.

**Comment by jonggul2** [comment]
Thank you.
